### ISSUE TITLE
Stop stealing my work

### ISSUE THREAD

**Issue by phpcore** [TheMuppets/proprietary_vendor_zuk#8]
Mrs Diogo Ferreira;

I charge you to stop you appropriate my source code for the "Hipay payment gateway for opencart". I know all about the dirty things you did with Johan Protin from Hipay group and the github repository with the full code of my work. I just did a reclamation about your dirty job at the Hi-media group. It's the last warning and if you still doing that I'll sue you.

**Comment by defer** [comment]
Go ahead. I also have no idea what you're talking about.

**Comment by rmcc** [comment]
LOL
